version: '3.9'
services:
 frontend:
    container_name: frontend
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - backend

 backend:
    container_name: backend
    build: ./
    ports:
      - "8080:8080"
